### ISSUE TITLE
Video names to play?

### ISSUE THREAD

**Issue by sylvia-sable** [theirc/Tunakujenga#14]
What should our videos be saved as in order to play in the app? 

Current compressed videos are here: https://drive.google.com/drive/folders/1yC0ELW6CUrTjPOzcHHRUOlvWQ8fMlPLZ

Can we use the existing video titles so they can play without editing the titles on our end? I've already shared them with our field team so this would help avoid another step of coordination. 

Let me know

**Comment by secretrobotron** [comment]
@sylvia-sable I put all the names in as they were listed in the asset list. Just copy n' paste :).
