### ISSUE TITLE
Scroll on quizzes

### ISSUE THREAD

**Issue by sylvia-sable** [theirc/Tunakujenga#9]
It would be ideal to be able to hold the app horizontally and vertically.

When I hold it horizontally and try to scroll through the quiz, the answers meld together.

See video: https://photos.app.goo.gl/55wGQxsrjvot1oN39

Possible to fix? If not, I can set the tablet orientation to stay vertical.

**Comment by ryanwarsaw** [comment]
Fixed in #17
